[package]
name = "enigma-service"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.3"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
enigma-auth= { path = "../../../../shared/auth/rust/enigma-auth" }
enigma-auth-grpc= { path = "../../../../shared/auth/rust/enigma-auth-grpc" }
enigma-auth-service = { path = "../../../../shared/auth/rust/enigma-auth-service", features = ["grpc"] }
