syntax = "proto3";

package auth;

service Auth {
    rpc CreateAccount (CreateAccountRequest) returns (CreateAccountReply);
    rpc DeleteAccount (DeleteAccountRequest) returns (DeleteAccountReply);
    rpc AddRole (AddRoleRequest) returns (AddRoleReply);
    rpc RemoveRole (RemoveRoleRequest) returns (RemoveRoleReply);
    rpc GetUserInfo (GetUserInfoRequest) returns (GetUserInfoReply);
    rpc ChangePassword (ChangePasswordRequest) returns (ChangePasswordReply);
    rpc RefreshSession (RefreshSessionRequest) returns (RefreshSessionReply);
    rpc Login (LoginRequest) returns (LoginReply);
    rpc ListAccounts (ListAccountsRequest) returns (ListAccountsReply);
    rpc GetSession (GetSessionRequest) returns (GetSessionReply);
    rpc PurgeExpiredSessions (PurgeExpiredSessionsRequest) returns (PurgeExpiredSessionsReply);
}

message CreateAccountRequest {
    string username = 1;
    string password = 2;
}

message CreateAccountReply {
    int64 user_id = 1;
}

message DeleteAccountRequest {
    int64 user_id = 1;
}

message DeleteAccountReply {
}

message AddRoleRequest {
    int64 user_id = 1;
    string role = 2;
}

message AddRoleReply {}

message RemoveRoleRequest {
    int64 user_id = 1;
    string role = 2;
}

message RemoveRoleReply {}

message GetUserInfoRequest {
    int64 user_id = 1;
}

message GetUserInfoReply {
    int64 user_id = 1;
    string username = 2;
    repeated string roles = 3;
}

message ChangePasswordRequest {
    int64 user_id = 1;
    string old_password = 2;
    string new_password = 3;
}

message ChangePasswordReply {
}

message RefreshSessionRequest {
    string refresh_token = 1;
}

message RefreshSessionReply {
    string access_token = 1;
    string refresh_token = 2;
}

message LoginRequest {
    string name = 1;
    string password = 2;
}

message LoginReply {
    int64 user_id = 1;
    string access_token = 2;
    string refresh_token = 3;
}

message ListAccountsRequest {
}

message ListAccountsReply {
    repeated User users = 1;
}

message User {
    int64 id = 1;
    string name = 2;
}

message GetSessionRequest {
    string access_token = 1;
}

message GetSessionReply {
    int64 user_id = 1;
}

message PurgeExpiredSessionsRequest {
}

message PurgeExpiredSessionsReply {
    uint64 purged_session_count = 1;
}
