syntax = "proto3";

package profiles;

service Profiles {
    rpc CreateProfile (CreateProfileRequest) returns (CreateProfileReply);
    rpc DeleteProfile (DeleteProfileRequest) returns (DeleteProfileReply);
    rpc GetProfile (GetProfileRequest) returns (GetProfileReply);
    rpc UpdateProfile (UpdateProfileRequest) returns (UpdateProfileReply);

    rpc RequestConnection (RequestConnectionRequest) returns (RequestConnectionReply);
    rpc AcceptConnection (AcceptConnectionRequest) returns (AcceptConnectionReply);
    rpc RejectConnection (RejectConnectionRequest) returns (RejectConnectionReply);

    rpc GetConnections (GetConnectionsRequest) returns (GetConnectionsReply);
    rpc AddConnection (AddConnectionRequest) returns (AddConnectionReply);
    rpc RemoveConnection (RemoveConnectionRequest) returns (RemoveConnectionReply);
    rpc UpdateConnection (UpdateConnectionRequest) returns (UpdateConnectionReply);
}

message CreateProfileRequest {
    UserProfile profile = 1;
}

message CreateProfileReply {
}

message DeleteProfileRequest {
    int64 user_id = 1;
}

message DeleteProfileReply {
}

message GetProfileRequest {
    int64 user_id = 1;
}

message GetProfileReply {
    UserProfile profile = 1;
}

message UpdateProfileRequest {
    UserProfile profile = 1;
}

message UpdateProfileReply {
}

message RequestConnectionRequest {
    int64 user_id = 1;
    int64 connection_id = 2;
    string kind = 3;
}

message RequestConnectionReply {
}

message AcceptConnectionRequest {
    int64 user_id = 1;
    int64 connection_id = 2;
    string kind = 3;
}

message AcceptConnectionReply {
}

message RejectConnectionRequest {
    int64 user_id = 1;
    int64 connection_id = 2;
}

message RejectConnectionReply {
}

message GetConnectionsRequest {
    int64 user_id = 1;
}

message GetConnectionsReply {
    repeated Connection connections = 1;
}

message Connection {
    string kind = 1;
    UserProfile profile = 2;
}

message AddConnectionRequest {
    int64 user_id = 1;
    int64 connection_user_id = 2;
    string kind = 3;
}

message AddConnectionReply {
}

message RemoveConnectionRequest {
    int64 user_id = 1;
    int64 connection_user_id = 2;
}

message RemoveConnectionReply {
}

message UpdateConnectionRequest {
    int64 user_id = 1;
    int64 connection_user_id = 2;
    string kind = 3;
}

message UpdateConnectionReply {
}

message UserProfile {
    int64 user_id = 1;
    string legal_name = 2;
    string display_name = 3;
    string profile_picture_url = 4;
    string primary_email = 5;
    int64 date_of_birth = 6;
}

enum ConnectionStatus {
    CONNECTION_STATUS_UNSPECIFIED = 0;
    CONNECTION_STATUS_REQUEST_SENT = 1;
    CONNECTION_STATUS_REQUESTED = 2;
    CONNECTION_STATUS_CONNECTED = 3;
    CONNECTION_STATUS_DENIED = 4;
    CONNECTION_STATUS_FOLLOWER = 5;
    CONNECTION_STATUS_FOLLOWED = 6;
    CONNECTION_STATUS_GHOST = 7;
}
