syntax = "proto3";

import "google/protobuf/timestamp.proto";

package profiles;

service Profiles {
    rpc CreateProfile (CreateProfileRequest) returns (CreateProfileReply);
    rpc DeleteProfile (DeleteProfileRequest) returns (DeleteProfileReply);
    rpc GetProfile (GetProfileRequest) returns (GetProfileReply);
    rpc UpdateProfile (UpdateProfileRequest) returns (UpdateProfileReply);
    rpc SearchProfiles (SearchProfilesRequest) returns (SearchProfilesReply);

    rpc RequestConnection (RequestConnectionRequest) returns (RequestConnectionReply);
    rpc AcceptConnection (AcceptConnectionRequest) returns (AcceptConnectionReply);
    rpc RejectConnection (RejectConnectionRequest) returns (RejectConnectionReply);

    rpc ListConnections (ListConnectionsRequest) returns (ListConnectionsReply);
    rpc AddConnection (AddConnectionRequest) returns (AddConnectionReply);
    rpc RemoveConnection (RemoveConnectionRequest) returns (RemoveConnectionReply);
    rpc UpdateConnection (UpdateConnectionRequest) returns (UpdateConnectionReply);

    rpc CreatePost (CreatePostRequest) returns (CreatePostReply);
    rpc DeletePost (DeletePostRequest) returns (DeletePostReply);
    rpc ListProfilePosts (ListProfilePostsRequest) returns (ListProfilePostsReply);
    rpc ListFeedPosts (ListFeedPostsRequest) returns (ListFeedPostsReply);
}

// Profiles

message UserProfile {
    int64 user_id = 1;
    string legal_name = 2;
    string display_name = 3;
    string profile_picture_url = 4;
    string primary_email = 5;
    int64 date_of_birth = 6;
}

message CreateProfileRequest {
    UserProfile profile = 1;
}

message CreateProfileReply {
}

message DeleteProfileRequest {
    int64 user_id = 1;
}

message DeleteProfileReply {
}

message GetProfileRequest {
    int64 user_id = 1;
}

message GetProfileReply {
    UserProfile profile = 1;
}

message UpdateProfileRequest {
    UserProfile profile = 1;
}

message UpdateProfileReply {
}

message SearchProfilesRequest {
    string query = 1;
}

message SearchProfilesReply {
    repeated UserProfile profiles = 1;
}

// Connections

message RequestConnectionRequest {
    int64 user_id = 1;
    int64 peer_id = 2;
    string relationship = 3;
}

message RequestConnectionReply {
    Connection connection = 1;
}

message AcceptConnectionRequest {
    int64 user_id = 1;
    int64 peer_id = 2;
    string relationship = 3;
}

message AcceptConnectionReply {
    Connection connection = 1;
}

message RejectConnectionRequest {
    int64 user_id = 1;
    int64 peer_id = 2;
}

message RejectConnectionReply {
}

message ListConnectionsRequest {
    int64 user_id = 1;
    repeated ConnectionStatus status_filter = 2;
    optional string cursor = 3;
    optional uint32 limit = 4;
}

message ListConnectionsReply {
    repeated Connection connections = 1;
    string next_cursor = 2;
    bool has_more = 3;
}

message Connection {
    string connection_id = 1;
    int64 user_id = 2;
    int64 peer_id = 3;
    string relationship = 4;
    ConnectionStatus status = 5;
    google.protobuf.Timestamp created_at = 6;
    google.protobuf.Timestamp updated_at = 7;
    UserProfile profile = 8;
}

message AddConnectionRequest {
    int64 user_id = 1;
    int64 peer_id = 2;
    string relationship = 3;
}

message AddConnectionReply {
    Connection connection = 1;
}

message RemoveConnectionRequest {
    int64 user_id = 1;
    int64 peer_id = 2;
}

message RemoveConnectionReply {
}

message UpdateConnectionRequest {
    int64 user_id = 1;
    int64 peer_id = 2;
    string relationship = 3;
}

message UpdateConnectionReply {
    Connection connection = 1;
}

enum ConnectionStatus {
    CONNECTION_STATUS_UNSPECIFIED = 0;
    CONNECTION_STATUS_REQUEST_SENT = 1;
    CONNECTION_STATUS_REQUESTED = 2;
    CONNECTION_STATUS_CONNECTED = 3;
    CONNECTION_STATUS_DELETED = 4;
    CONNECTION_STATUS_DENIED = 5;
    CONNECTION_STATUS_FOLLOWER = 6;
    CONNECTION_STATUS_FOLLOWED = 7;
    CONNECTION_STATUS_GHOST = 8;
}


// Posts

message CreatePostRequest {
    reserved 2; // Audience
    int64 user_id = 1;
    // Audience: List of categories?
    string content = 3;
}

message CreatePostReply {
    string post_id = 1;
}

message DeletePostRequest {
    string post_id = 1;
}

message DeletePostReply {
}

message ListProfilePostsRequest {
    int64 user_id = 1;
}

message ListProfilePostsReply {
    repeated Post posts = 1;
}

message ListFeedPostsRequest {
    reserved 2; // Filter? Only get posts from some connections? Timeframe?
    int64 user_id = 1;
}

message ListFeedPostsReply {
    repeated Post posts = 1;
}

message Post {
    reserved 6; // Audience

    string post_id = 1;
    int64 user_id = 2;
    UserProfile user_profile = 3;
    int64 created_at = 4;
    int64 updated_at = 5;
    string content = 7;
}
