[package]
name = "foorum-auth-client"
version = "0.1.0"
edition = "2021"

[features]
grpc = ["dep:foorum-auth-grpc"]

[dependencies]
foorum-auth = { path = "../foorum-auth" }
foorum-auth-grpc = { path = "../foorum-auth-grpc", optional = true }
tonic = "0.12.3"
uuid = { version = "1.11.0", features = ["v4"] }
