[package]
name = "enigma-auth-service"
version = "0.1.0"
edition = "2021"

[features]
default = ["grpc"]
grpc = ["dep:enigma-auth-grpc"]

[dependencies]
argon2 = "0.5.3"
async-trait = "0.1.85"
chrono = "0.4.39"
dotenvy = "0.15.7"
enigma-auth = { path = "../enigma-auth" }
enigma-auth-grpc = { path = "../enigma-auth-grpc", optional = true }
sqlx = { version = "0.8.3", features = ["chrono", "postgres", "runtime-tokio-native-tls", "uuid"] }
tokio = "1.43.0"
tonic = "0.12.3"
tracing = "0.1.41"
uuid = { version = "1.12.0", features = ["v4"] }
