[package]
name = "enigma-auth-client"
version = "0.1.0"
edition = "2021"

[features]
default = ["grpc"]
grpc = ["dep:enigma-auth-grpc"]

[dependencies]
async-trait = "0.1.85"
enigma-auth = { path = "../enigma-auth" }
enigma-auth-grpc = { path = "../enigma-auth-grpc", optional = true }
http-body = "1.0.1"
mockall = "0.13.1"
serde = { version = "1.0.217", features = ["derive"] }
tokio = "1.43.0"
toml = "0.8.19"
tonic = "0.12.3"
tracing = "0.1.41"
uuid = { version = "1.11.0", features = ["v4"] }
